"""Add DocKeyword, DocumentAudio, DocumentSave, DocumentView, EmailVerification models

Revision ID: 1bf2c3a02c3e
Revises: 62921a152872
Create Date: 2025-06-12 09:54:54.620640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf2c3a02c3e'
down_revision = '62921a152872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_emailverification_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verifications_user_id'), ['user_id'], unique=False)

    op.create_table('doc_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_dockeyword_document_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doc_keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doc_keywords_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doc_keywords_keyword'), ['keyword'], unique=False)

    op.create_table('document_audios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_documentaudio_document_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_audios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_audios_document_id'), ['document_id'], unique=False)

    op.create_table('document_saves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_documentsave_document_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_documentsave_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_id', name='uq_user_document_save')
    )
    with op.batch_alter_table('document_saves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_saves_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_saves_user_id'), ['user_id'], unique=False)

    op.create_table('document_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_documentview_document_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_documentview_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_views_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_views_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_views_document_id'))

    op.drop_table('document_views')
    with op.batch_alter_table('document_saves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_saves_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_saves_document_id'))

    op.drop_table('document_saves')
    with op.batch_alter_table('document_audios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_audios_document_id'))

    op.drop_table('document_audios')
    with op.batch_alter_table('doc_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doc_keywords_keyword'))
        batch_op.drop_index(batch_op.f('ix_doc_keywords_document_id'))

    op.drop_table('doc_keywords')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verifications_token'))

    op.drop_table('email_verifications')
    # ### end Alembic commands ###
