"""Add Notification, DocumentLike, Referral, RewardPoint, RedeemTransaction models

Revision ID: 2f7f093c94b6
Revises: 3d858c3029f2
Create Date: 2025-06-12 09:30:27.865518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7f093c94b6'
down_revision = '3d858c3029f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='fk_notification_sender_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redeem_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points_redeemed', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_redeemtransaction_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redeem_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redeem_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('reward_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('referral_code_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_rewardpoint_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_points_referral_code_used'), ['referral_code_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_points_user_id'), ['user_id'], unique=False)

    op.create_table('document_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_documentlike_document_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_documentlike_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_id', name='uq_user_document_like')
    )
    with op.batch_alter_table('document_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_likes_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_likes_user_id'), ['user_id'], unique=False)

    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('referral_code_used', sa.String(length=50), nullable=False),
    sa.Column('points_awarded_to_referrer', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reward_point_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], name='fk_referral_referred_id'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name='fk_referral_referrer_id'),
    sa.ForeignKeyConstraint(['reward_point_id'], ['reward_points.id'], name='fk_referral_reward_point_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reward_point_id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_referral_code_used'), ['referral_code_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_referred_id'), ['referred_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_referrals_referrer_id'), ['referrer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_referrer_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_referred_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_referral_code_used'))

    op.drop_table('referrals')
    with op.batch_alter_table('document_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_likes_document_id'))

    op.drop_table('document_likes')
    with op.batch_alter_table('reward_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_points_user_id'))
        batch_op.drop_index(batch_op.f('ix_reward_points_referral_code_used'))

    op.drop_table('reward_points')
    with op.batch_alter_table('redeem_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redeem_transactions_user_id'))

    op.drop_table('redeem_transactions')
    op.drop_table('notifications')
    # ### end Alembic commands ###
