"""Add Contact and Invoice models

Revision ID: 374dc5201b8a
Revises: 1bf2c3a02c3e
Create Date: 2025-06-12 10:01:53.013779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374dc5201b8a'
down_revision = '1bf2c3a02c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_contact_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_user_id'), ['user_id'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=120), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stripe_subscription_id'], ['subscriptions.stripe_subscription_id'], name='fk_invoice_stripe_subscription_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_invoice_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_stripe_invoice_id'), ['stripe_invoice_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoice_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_user_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_stripe_invoice_id'))

    op.drop_table('invoice')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_user_id'))

    op.drop_table('contacts')
    # ### end Alembic commands ###
