"""Add Category, DocumentType, FAQ models, Payment table, and update User, Document, Plan

Revision ID: 3d858c3029f2
Revises: 735940cf5b85
Create Date: 2025-06-12 09:22:47.907848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d858c3029f2'
down_revision = '735940cf5b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qcode', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cover', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_downloadable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('document_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('author_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('author_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('author_desc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('num_pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('listen_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('read_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('original_file_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_document_type_id'), ['document_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_qcode'), ['qcode'], unique=True)
        batch_op.create_foreign_key('fk_document_category_id', 'categories', ['category_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key('fk_document_document_type_id', 'document_types', ['document_type_id'], ['id'], use_alter=True)
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_type')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))
        batch_op.drop_column('features')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('referral_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('api_key', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ref_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('reg_source', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=True)
        batch_op.create_foreign_key('fk_user_ref_user_id', 'users', ['ref_user_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key('fk_user_role_id', 'roles', ['role_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_role_id', type_='foreignkey')
        batch_op.drop_constraint('fk_user_ref_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.drop_index(batch_op.f('ix_users_api_key'))
        batch_op.drop_column('reg_source')
        batch_op.drop_column('dob')
        batch_op.drop_column('last_active')
        batch_op.drop_column('role_id')
        batch_op.drop_column('ref_user_id')
        batch_op.drop_column('status_id')
        batch_op.drop_column('api_key')
        batch_op.drop_column('referral_code')
        batch_op.drop_column('user_image')
        batch_op.drop_column('description')
        batch_op.drop_column('country')
        batch_op.drop_column('phone')
        batch_op.drop_column('stripe_customer_id')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features', sa.TEXT(), nullable=True))
        batch_op.drop_column('is_available')
        batch_op.drop_column('description')
        batch_op.drop_column('currency')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint('fk_document_document_type_id', type_='foreignkey')
        batch_op.drop_constraint('fk_document_category_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_qcode'))
        batch_op.drop_index(batch_op.f('ix_documents_document_type_id'))
        batch_op.drop_index(batch_op.f('ix_documents_category_id'))
        batch_op.drop_column('notes')
        batch_op.drop_column('original_file_type')
        batch_op.drop_column('is_published')
        batch_op.drop_column('tags')
        batch_op.drop_column('read_time')
        batch_op.drop_column('listen_time')
        batch_op.drop_column('price')
        batch_op.drop_column('num_pages')
        batch_op.drop_column('author_desc')
        batch_op.drop_column('author_link')
        batch_op.drop_column('author_name')
        batch_op.drop_column('category_id')
        batch_op.drop_column('document_type_id')
        batch_op.drop_column('is_downloadable')
        batch_op.drop_column('cover')
        batch_op.drop_column('link')
        batch_op.drop_column('qcode')

    # ### end Alembic commands ###
