"""Add Status, StoreTag, FreeTrial, AppUsage, Testimonial models and update User relationships

Revision ID: 5eefe3e4658e
Revises: 374dc5201b8a
Create Date: 2025-06-12 10:08:54.015577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eefe3e4658e'
down_revision = '374dc5201b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=120), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('caller_info', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_usage_api_key'), ['api_key'], unique=False)

    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('store_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('qcode', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('store_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_tags_qcode'), ['qcode'], unique=True)

    op.create_table('free_trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name='fk_freetrial_plan_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_freetrial_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('free_trials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_free_trials_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_free_trials_user_id'), ['user_id'], unique=False)

    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_testimonial_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_testimonials_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_status_id'), ['status_id'], unique=False)
        batch_op.create_foreign_key('fk_user_status_id', 'status', ['status_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_status_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_status_id'))

    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_testimonials_user_id'))

    op.drop_table('testimonials')
    with op.batch_alter_table('free_trials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_free_trials_user_id'))
        batch_op.drop_index(batch_op.f('ix_free_trials_plan_id'))

    op.drop_table('free_trials')
    with op.batch_alter_table('store_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_tags_qcode'))

    op.drop_table('store_tags')
    op.drop_table('status')
    with op.batch_alter_table('app_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_usage_api_key'))

    op.drop_table('app_usage')
    # ### end Alembic commands ###
