"""Add Activity, DocumentReview, SiteSetting models

Revision ID: 62921a152872
Revises: 2f7f093c94b6
Create Date: 2025-06-12 09:35:41.914909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62921a152872'
down_revision = '2f7f093c94b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('who_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['who_id'], ['users.id'], name='fk_activity_who_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('maintenance_on', sa.Boolean(), nullable=False),
    sa.Column('banner_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('document_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_review_document_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_review_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_id', name='uq_user_document_review')
    )
    with op.batch_alter_table('document_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_reviews_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_reviews_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_reviews_document_id'))

    op.drop_table('document_reviews')
    op.drop_table('site_settings')
    op.drop_table('activities')
    # ### end Alembic commands ###
